import { phpString } from '../security/php.js';

export const PROVIDER_IDS = ['mirza', 'faoxima', 'pasarguard'] as const;
export type ProviderId = (typeof PROVIDER_IDS)[number];

export interface ProviderContext {
  domain: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  botToken: string;
  botUsername: string;
  adminTelegramId: string;
  /** FleetPanel's per-instance webhook secret ([A-Za-z0-9_-], 32+ chars). */
  webhookSecret: string;
  /** Absolute instance directory. */
  instanceDir: string;
  /** Telegram API credentials from my.telegram.org (providers that log in over MTProto). */
  apiId?: string;
  apiHash?: string;
  /** Loopback port of the bot's own web server (service providers). */
  appPort?: number;
}

/** Inputs a provider needs on top of the common ones (bot token, admin id, domain). */
export type ExtraField = 'api_id' | 'api_hash';

/**
 * How Telegram proves a webhook call is genuine. It must match what the bot checks
 * itself, because the bot also re-registers its own webhook from its admin panel:
 * - header: X-Telegram-Bot-Api-Secret-Token (Telegram's secret_token)
 * - query:  ?secret=… in the webhook URL
 */
export type WebhookAuth = 'header' | 'query';

interface ProviderBase {
  id: ProviderId;
  displayName: string;
  repoUrl: string;
  /**
   * The exact upstream commit FleetPanel installs (40-hex id). Never a branch or tag: those can be
   * moved by whoever controls the upstream repository. Bump it only after reviewing the upstream
   * changes, in a FleetPanel release (see docs/providers.md).
   */
  commit: string;
  /** Human-readable label for that commit, shown in the panel. */
  version: string;
  extraFields: ExtraField[];
  /**
   * The bot's own web page the panel links to. Not the site root: for the PHP bots that is the
   * Telegram webhook, which nginx answers with 403 unless the request carries the secret.
   */
  webPath: string;
}

/** A PHP bot served by PHP-FPM; Telegram delivers updates to its webhook. */
export interface PhpProvider extends ProviderBase {
  runtime: 'php';
  /** Path (relative to the web root) Telegram posts updates to. */
  webhookPath: string;
  webhookAuth: WebhookAuth;
  /** The project's config file, relative to the instance directory. Its shipped template is patched in place. */
  configFile: string;
  /** Upstream web installer directory. Removed before the site goes live: it must never be reachable. */
  installerDir: string;
  /** Schema/bootstrap script run with the PHP CLI once the database exists. */
  schemaScript: string;
  /** Fills the upstream config template. Throws if the template no longer has the expected shape. */
  renderConfig(template: string, ctx: ProviderContext): string;
  /** Optional SQL run after the schema script (values are validated, so they are safe to inline). */
  postSchemaSql?(ctx: ProviderContext): string;
  /** A query returning one number; provisioning fails unless it is > 0 (proves the schema and setup took). */
  readyCheckSql(ctx: ProviderContext): string;
  webhookUrl(ctx: ProviderContext): string;
}

/**
 * A Python bot that runs as a long-lived systemd service (it connects to Telegram itself),
 * with its own Redis and its web server reachable only through nginx.
 */
export interface PythonProvider extends ProviderBase {
  runtime: 'python';
  /** The service's environment. Keys must be on the helper's allowlist, values in its charset. */
  renderEnv(ctx: ProviderContext): Record<string, string>;
  /** A query returning one number; provisioning fails unless it is > 0. */
  readyCheckSql(ctx: ProviderContext): string;
}

export type BotProvider = PhpProvider | PythonProvider;

/** First loopback port for service bots; an instance uses APP_PORT_BASE + its id. */
export const APP_PORT_BASE = 20000;

function required(value: string | undefined, name: string): string {
  if (!value) throw new Error(`${name} is missing`);
  return value;
}

const GENERATED = '// Generated by FleetPanel. Manual edits are overwritten when the instance is reprovisioned.';
const SECRET_RE = /^[A-Za-z0-9_-]{32,256}$/;

function checkedSecret(secret: string): string {
  if (!SECRET_RE.test(secret)) throw new Error('invalid webhook secret');
  return secret;
}

function checkedId(id: string): string {
  if (!/^\d{1,20}$/.test(id)) throw new Error('invalid Telegram id');
  return id;
}

function addHeader(source: string): string {
  if (!source.startsWith('<?php')) throw new Error('provider config template does not start with <?php');
  return source.replace('<?php', `<?php\n${GENERATED}`);
}

/** Replaces each quoted placeholder ('{name}') with a safely escaped PHP literal. */
function fillPlaceholders(template: string, values: Record<string, string>): string {
  let out = template;
  for (const [name, value] of Object.entries(values)) {
    const token = `'{${name}}'`;
    if (!out.includes(token)) {
      throw new Error(`provider config template has no ${token} placeholder; the upstream project changed its config format`);
    }
    out = out.split(token).join(phpString(value));
  }
  return out;
}

/** Sets `$name = '';` (first occurrence, at line start) to a safely escaped PHP literal. */
function fillEmptyAssignments(template: string, values: Record<string, string>): string {
  let out = template;
  for (const [name, value] of Object.entries(values)) {
    const re = new RegExp(`^(\\$${name}\\s*=\\s*)''(\\s*;)`, 'm');
    if (!re.test(out)) {
      throw new Error(`provider config template has no empty $${name} assignment; the upstream project changed its config format`);
    }
    out = out.replace(re, (_m, lhs: string, end: string) => `${lhs}${phpString(value)}${end}`);
  }
  return out;
}

// Both projects ship config.php as a template and expect their web installer to fill it,
// create the schema (table.php) and register the webhook. FleetPanel performs those steps
// itself and removes the installer. Re-check these when bumping a provider version.
export const PROVIDERS: Record<ProviderId, BotProvider> = {
  mirza: {
    id: 'mirza',
    displayName: 'MirzaBot',
    repoUrl: 'https://github.com/mahdiMGF2/mirzabot.git',
    commit: '8e551ecf73d18dac8cb4b0cbada64c041e660f32',
    version: 'main @ 2026-10-02',
    extraFields: [],
    webPath: 'panel/',
    runtime: 'php',
    webhookPath: 'index.php',
    // index.php compares ?secret= with setting.webhook_secret and re-registers the
    // webhook with that query string, never with a secret_token header.
    webhookAuth: 'query',
    configFile: 'config.php',
    installerDir: 'install',
    schemaScript: 'table.php',
    renderConfig: (template, c) =>
      addHeader(
        fillPlaceholders(template, {
          database_url: 'localhost',
          database_name: c.dbName,
          username_db: c.dbUser,
          password_db: c.dbPassword,
          API_KEY: c.botToken,
          admin_number: c.adminTelegramId,
          domain_name: c.domain,
          username_bot: c.botUsername,
        }),
      ),
    postSchemaSql: (c) => `UPDATE setting SET webhook_secret = '${checkedSecret(c.webhookSecret)}';`,
    readyCheckSql: (c) => `SELECT COUNT(*) FROM setting WHERE webhook_secret = '${checkedSecret(c.webhookSecret)}';`,
    webhookUrl: (c) => `https://${c.domain}/index.php?secret=${checkedSecret(c.webhookSecret)}`,
  },
  faoxima: {
    id: 'faoxima',
    displayName: 'Faoxima',
    repoUrl: 'https://github.com/Mmd-Amir/Faoxima.git',
    commit: '68eccf1981f1bd7f21c8000ad5fff198a0f6c175',
    version: 'v1.1.5',
    extraFields: [],
    webPath: 'panel/',
    runtime: 'php',
    webhookPath: 'index.php',
    // FaoximaWebhookAuth checks the secret_token header against TELEGRAM_WEBHOOK_SECRET.
    webhookAuth: 'header',
    configFile: 'config.php',
    installerDir: 'installer',
    schemaScript: 'table.php',
    renderConfig: (template, c) => {
      const filled = fillEmptyAssignments(template, {
        dbname: c.dbName,
        usernamedb: c.dbUser,
        passworddb: c.dbPassword,
        dbhost: 'localhost',
        APIKEY: c.botToken,
        adminnumber: c.adminTelegramId,
        domainhosts: c.domain,
        usernamebot: c.botUsername,
      });
      const secret = phpString(checkedSecret(c.webhookSecret));
      return filled.replace(
        '<?php',
        `<?php\n${GENERATED}\nif (!defined('TELEGRAM_WEBHOOK_SECRET')) {\n    define('TELEGRAM_WEBHOOK_SECRET', ${secret});\n}`,
      );
    },
    // table.php creates the admin row for $adminnumber; fail provisioning if it did not.
    readyCheckSql: (c) => `SELECT COUNT(*) FROM admin WHERE id_admin = '${checkedId(c.adminTelegramId)}';`,
    webhookUrl: (c) => `https://${c.domain}/index.php`,
  },
  pasarguard: {
    id: 'pasarguard',
    displayName: 'PasarguardBot',
    repoUrl: 'https://github.com/AmirKenzo/PasarguardBot.git',
    commit: 'f9c7c28c99bd9c5d394e68c6e27ae545fa6762aa',
    version: 'v2.1.4',
    // Telethon logs in over MTProto, which needs an API id/hash besides the bot token.
    extraFields: ['api_id', 'api_hash'],
    webPath: 'webapp/',
    runtime: 'python',
    renderEnv: (c) => ({
      BOT_TOKEN: c.botToken,
      API_ID: required(c.apiId, 'API id'),
      API_HASH: required(c.apiHash, 'API hash'),
      ADMIN_ID: checkedId(c.adminTelegramId),
      // MySQL's local socket, like the PHP bots: the database user exists for 'localhost' only.
      SQLALCHEMY_DATABASE_URL: `mysql+asyncmy://${c.dbUser}:${c.dbPassword}@localhost/${c.dbName}?unix_socket=/run/mysqld/mysqld.sock`,
      FASTAPI_PORT: required(c.appPort ? String(c.appPort) : undefined, 'app port'),
      REDIS_URL: `unix://${c.instanceDir}/data/redis/redis.sock`,
      REDIS_NAMESPACE_PREFIX: `fleetpanel:${c.dbName}`,
      LOG_DIR: `${c.instanceDir}/logs`,
      TELETHON_SESSION_PATH: `${c.instanceDir}/sessions/bot`,
      WEBAPP_URL: `https://${c.domain}/webapp`,
    }),
    // Alembic records the applied revision once the schema exists.
    readyCheckSql: () => 'SELECT COUNT(*) FROM alembic_version;',
  },
};
