import { phpString } from '../security/php.js';

export const PROVIDER_IDS = ['mirza', 'faoxima'] as const;
export type ProviderId = (typeof PROVIDER_IDS)[number];

export interface ProviderContext {
  domain: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  botToken: string;
  botUsername: string;
  adminTelegramId: string;
  /** FleetPanel's per-instance webhook secret ([A-Za-z0-9_-], 32+ chars). */
  webhookSecret: string;
}

/**
 * How Telegram proves a webhook call is genuine. It must match what the bot checks
 * itself, because the bot also re-registers its own webhook from its admin panel:
 * - header: X-Telegram-Bot-Api-Secret-Token (Telegram's secret_token)
 * - query:  ?secret=… in the webhook URL
 */
export type WebhookAuth = 'header' | 'query';

export interface BotProvider {
  id: ProviderId;
  displayName: string;
  repoUrl: string;
  /** Git branch or tag to deploy. Undefined = upstream default branch. */
  ref?: string;
  /** Path (relative to the web root) Telegram posts updates to. */
  webhookPath: string;
  webhookAuth: WebhookAuth;
  /** The project's config file, relative to the instance directory. Its shipped template is patched in place. */
  configFile: string;
  /** Upstream web installer directory. Removed before the site goes live: it must never be reachable. */
  installerDir: string;
  /** Schema/bootstrap script run with the PHP CLI once the database exists. */
  schemaScript: string;
  /** Fills the upstream config template. Throws if the template no longer has the expected shape. */
  renderConfig(template: string, ctx: ProviderContext): string;
  /** Optional SQL run after the schema script (values are validated, so they are safe to inline). */
  postSchemaSql?(ctx: ProviderContext): string;
  /** A query returning one number; provisioning fails unless it is > 0 (proves the schema and setup took). */
  readyCheckSql(ctx: ProviderContext): string;
  webhookUrl(ctx: ProviderContext): string;
}

const GENERATED = '// Generated by FleetPanel. Manual edits are overwritten when the instance is reprovisioned.';
const SECRET_RE = /^[A-Za-z0-9_-]{32,256}$/;

function checkedSecret(secret: string): string {
  if (!SECRET_RE.test(secret)) throw new Error('invalid webhook secret');
  return secret;
}

function checkedId(id: string): string {
  if (!/^\d{1,20}$/.test(id)) throw new Error('invalid Telegram id');
  return id;
}

function addHeader(source: string): string {
  if (!source.startsWith('<?php')) throw new Error('provider config template does not start with <?php');
  return source.replace('<?php', `<?php\n${GENERATED}`);
}

/** Replaces each quoted placeholder ('{name}') with a safely escaped PHP literal. */
function fillPlaceholders(template: string, values: Record<string, string>): string {
  let out = template;
  for (const [name, value] of Object.entries(values)) {
    const token = `'{${name}}'`;
    if (!out.includes(token)) {
      throw new Error(`provider config template has no ${token} placeholder; the upstream project changed its config format`);
    }
    out = out.split(token).join(phpString(value));
  }
  return out;
}

/** Sets `$name = '';` (first occurrence, at line start) to a safely escaped PHP literal. */
function fillEmptyAssignments(template: string, values: Record<string, string>): string {
  let out = template;
  for (const [name, value] of Object.entries(values)) {
    const re = new RegExp(`^(\\$${name}\\s*=\\s*)''(\\s*;)`, 'm');
    if (!re.test(out)) {
      throw new Error(`provider config template has no empty $${name} assignment; the upstream project changed its config format`);
    }
    out = out.replace(re, (_m, lhs: string, end: string) => `${lhs}${phpString(value)}${end}`);
  }
  return out;
}

// Both projects ship config.php as a template and expect their web installer to fill it,
// create the schema (table.php) and register the webhook. FleetPanel performs those steps
// itself and removes the installer. Re-check these when bumping a provider version.
export const PROVIDERS: Record<ProviderId, BotProvider> = {
  mirza: {
    id: 'mirza',
    displayName: 'MirzaBot',
    repoUrl: 'https://github.com/mahdiMGF2/mirzabot.git',
    webhookPath: 'index.php',
    // index.php compares ?secret= with setting.webhook_secret and re-registers the
    // webhook with that query string, never with a secret_token header.
    webhookAuth: 'query',
    configFile: 'config.php',
    installerDir: 'install',
    schemaScript: 'table.php',
    renderConfig: (template, c) =>
      addHeader(
        fillPlaceholders(template, {
          database_url: 'localhost',
          database_name: c.dbName,
          username_db: c.dbUser,
          password_db: c.dbPassword,
          API_KEY: c.botToken,
          admin_number: c.adminTelegramId,
          domain_name: c.domain,
          username_bot: c.botUsername,
        }),
      ),
    postSchemaSql: (c) => `UPDATE setting SET webhook_secret = '${checkedSecret(c.webhookSecret)}';`,
    readyCheckSql: (c) => `SELECT COUNT(*) FROM setting WHERE webhook_secret = '${checkedSecret(c.webhookSecret)}';`,
    webhookUrl: (c) => `https://${c.domain}/index.php?secret=${checkedSecret(c.webhookSecret)}`,
  },
  faoxima: {
    id: 'faoxima',
    displayName: 'Faoxima',
    repoUrl: 'https://github.com/Mmd-Amir/Faoxima.git',
    webhookPath: 'index.php',
    // FaoximaWebhookAuth checks the secret_token header against TELEGRAM_WEBHOOK_SECRET.
    webhookAuth: 'header',
    configFile: 'config.php',
    installerDir: 'installer',
    schemaScript: 'table.php',
    renderConfig: (template, c) => {
      const filled = fillEmptyAssignments(template, {
        dbname: c.dbName,
        usernamedb: c.dbUser,
        passworddb: c.dbPassword,
        dbhost: 'localhost',
        APIKEY: c.botToken,
        adminnumber: c.adminTelegramId,
        domainhosts: c.domain,
        usernamebot: c.botUsername,
      });
      const secret = phpString(checkedSecret(c.webhookSecret));
      return filled.replace(
        '<?php',
        `<?php\n${GENERATED}\nif (!defined('TELEGRAM_WEBHOOK_SECRET')) {\n    define('TELEGRAM_WEBHOOK_SECRET', ${secret});\n}`,
      );
    },
    // table.php creates the admin row for $adminnumber; fail provisioning if it did not.
    readyCheckSql: (c) => `SELECT COUNT(*) FROM admin WHERE id_admin = '${checkedId(c.adminTelegramId)}';`,
    webhookUrl: (c) => `https://${c.domain}/index.php`,
  },
};
