import { phpString } from '../security/php.js';

export const PROVIDER_IDS = ['mirza', 'faoxima'] as const;
export type ProviderId = (typeof PROVIDER_IDS)[number];

export interface ProviderContext {
  domain: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  botToken: string;
  botUsername: string;
  adminTelegramId: string;
}

export interface BotProvider {
  id: ProviderId;
  displayName: string;
  repoUrl: string;
  /** Git branch or tag to deploy. Undefined = upstream default branch. */
  ref?: string;
  /** Path (relative to the web root) Telegram posts updates to. */
  webhookPath: string;
  /** Config file path relative to the instance directory. */
  configFile: string;
  renderConfig(ctx: ProviderContext): string;
}

const GENERATED = '<?php\n// Generated by Fleetbot. Manual edits are overwritten when the instance is reprovisioned.\n';

// Every interpolated value goes through phpString(), so no input can break out of
// its string literal. Variable names follow each project's own installer template;
// re-check them when bumping a provider to a new upstream version.
export const PROVIDERS: Record<ProviderId, BotProvider> = {
  mirza: {
    id: 'mirza',
    displayName: 'MirzaBot',
    repoUrl: 'https://github.com/mahdiMGF2/mirzabot.git',
    webhookPath: 'index.php',
    configFile: 'config.php',
    renderConfig: (c) => `${GENERATED}
$dbname = ${phpString(c.dbName)};
$usernamedb = ${phpString(c.dbUser)};
$passworddb = ${phpString(c.dbPassword)};
$connect = mysqli_connect('localhost', $usernamedb, $passworddb, $dbname);
mysqli_set_charset($connect, 'utf8mb4');
$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];
$pdo = new PDO('mysql:host=localhost;dbname=' . $dbname . ';charset=utf8mb4', $usernamedb, $passworddb, $options);
$APIKEY = ${phpString(c.botToken)};
$adminnumber = ${phpString(c.adminTelegramId)};
$domainhosts = ${phpString(c.domain)};
$usernamebot = ${phpString(c.botUsername)};
`,
  },
  faoxima: {
    id: 'faoxima',
    displayName: 'Faoxima',
    repoUrl: 'https://github.com/Mmd-Amir/Faoxima.git',
    webhookPath: 'index.php',
    configFile: 'config/config.php',
    renderConfig: (c) => `${GENERATED}
return [
    'bot_token' => ${phpString(c.botToken)},
    'bot_username' => ${phpString(c.botUsername)},
    'admin_id' => ${phpString(c.adminTelegramId)},
    'domain' => ${phpString(c.domain)},
    'db' => [
        'host' => 'localhost',
        'database' => ${phpString(c.dbName)},
        'username' => ${phpString(c.dbUser)},
        'password' => ${phpString(c.dbPassword)},
    ],
];
`,
  },
};
